### ISSUE TITLE
Connection closed - expected, I guess...

### ISSUE THREAD

**Issue by flozano** [tokuhirom/jetty-server_starter-sample#1]
Thanks a lot for this example.

I would like to confirm the behaviour I'm seeing:
1. I start your jetty example with Server::Starter 0.30:
   
   ```
   start_server --port=3333=0 -- java -jar build/libs/jetty-server_starter-sample-all-1.0.jar
   ```
2. I run a continuous HTTP request stream
   
   ```
   $ ab -n 10000 http://localhost:3333/
   ```
3. I do kill -SIGHUP <PID of start_server>. I see:
   
   ```
   new worker is now running, sending TERM to old workers:17221
   killing old workers
   ```
   
   (so in theory it's working)
4. sometimes (many) my "ab" process dies in error. it seems the restart is not so graceful:
   
   ```
   Benchmarking localhost (be patient)
   Completed 1000 requests
   Completed 2000 requests
   apr_socket_recv: Connection reset by peer (104)
   Total of 2811 requests completed
   ```

I understand why the open connection is being closed - but, can I be sure that there wasn't an ongoing request being processed? I assumed that jetty is taking care of it, but from looking at jetty code I can't figure that out.

**Comment by tokuhirom** [comment]
Sorry, I forgot to enable graceful shutdown option on jetty. f7bc229 fix the issue.

**Comment by flozano** [comment]
oh, I didn't notice it wasn't enabled either... thanks!

**Comment by flozano** [comment]
BTW from setStopTimeout() code:

``` java
    /**
     * Set a graceful stop time.
     * The {@link StatisticsHandler} must be configured so that open connections can
     * be tracked for a graceful shutdown.
     * @see org.eclipse.jetty.util.component.ContainerLifeCycle#setStopTimeout(long)
     */
    @Override
    public void setStopTimeout(long stopTimeout)
    {
        super.setStopTimeout(stopTimeout);
    }
```

so it seems you need to add a StatisticsHandler too

**Comment by tokuhirom** [comment]
woot, i'll fix it soon

**Comment by tokuhirom** [comment]
Added statisticshandler!
